# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Casiusbot < Formula
  desc "A Discord bot (https://discord.com) with several features"
  homepage "https://github.com/dvaumoron/casiusbot"
  version "1.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.7.0/casiusbot_1.7.0_darwin_amd64.zip"
      sha256 "8b6c463699ef6eb897eee5d14583f3794605ce0568f1c0aa30b792b1d02d4ef4"

      def install
        bin.install "casiusbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.7.0/casiusbot_1.7.0_darwin_arm64.zip"
      sha256 "1ba46a7a0d3969100f898c3a88a721ded2948da34414924303f352e12f23d2d4"

      def install
        bin.install "casiusbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/casiusbot/releases/download/v1.7.0/casiusbot_1.7.0_linux_amd64.zip"
        sha256 "cdf484bdb961012d12b5dbf8e5d876d818a58374f9a0ad1ccdf8a3f49b878ff6"

        def install
          bin.install "casiusbot"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/casiusbot/releases/download/v1.7.0/casiusbot_1.7.0_linux_arm.zip"
        sha256 "924d713a9a4def2cb24d53220bff6c6c55877a4c988fd87f2dc2d0ad345cc646"

        def install
          bin.install "casiusbot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/casiusbot/releases/download/v1.7.0/casiusbot_1.7.0_linux_arm64.zip"
        sha256 "6f61a77a7835fd3f329ba7db25ec779c61f09df3f477e069324fa4f71514c390"

        def install
          bin.install "casiusbot"
        end
      end
    end
  end
end
