# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Casiusbot < Formula
  desc "A Discord bot (https://discord.com) with several features"
  homepage "https://github.com/dvaumoron/casiusbot"
  version "1.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.8.0/casiusbot_1.8.0_darwin_amd64.zip"
      sha256 "4783264dc44542acd8853860707f1c4092a6079921f1de5d361ec7b89e3f8f8d"

      def install
        bin.install "casiusbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.8.0/casiusbot_1.8.0_darwin_arm64.zip"
      sha256 "b8fd6e33b9d94a52f0d785275d62fc2e80a41d498c4a1e4adfc8797217070510"

      def install
        bin.install "casiusbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/casiusbot/releases/download/v1.8.0/casiusbot_1.8.0_linux_amd64.zip"
        sha256 "da7381a11bf3480e427dad2742cad97965cbc2a52e20d5cac185c80870cda37b"

        def install
          bin.install "casiusbot"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/casiusbot/releases/download/v1.8.0/casiusbot_1.8.0_linux_arm.zip"
        sha256 "cab311e4c83a767fe2ae3d79d8d6132ddc6f824141f37f324b933925b64422e1"

        def install
          bin.install "casiusbot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/casiusbot/releases/download/v1.8.0/casiusbot_1.8.0_linux_arm64.zip"
        sha256 "484c9300ca968839ef478a4002d23c2ef1e9c2fc63a46b437b4730c28fdf2d42"

        def install
          bin.install "casiusbot"
        end
      end
    end
  end
end
