# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Casiusbot < Formula
  desc "A Discord bot (https://discord.com) with several features"
  homepage "https://github.com/dvaumoron/casiusbot"
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.6.0/casiusbot_1.6.0_darwin_amd64.zip"
      sha256 "d84f8d8a109419c4e0872ec232453b4e4a8039f59d5f1636e48f6d2e23b8e7b1"

      def install
        bin.install "casiusbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.6.0/casiusbot_1.6.0_darwin_arm64.zip"
      sha256 "80da07542bd9278522582dfbc6e419b07fa639107127cf115c1aa2c1a4aea493"

      def install
        bin.install "casiusbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.6.0/casiusbot_1.6.0_linux_amd64.zip"
      sha256 "da0ecb6780ad748250eeabfae7c3ab825f1427fe40df090504d2f07e269a84a0"

      def install
        bin.install "casiusbot"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.6.0/casiusbot_1.6.0_linux_arm.zip"
      sha256 "fe4a7d66046dd243259205c37f915071b54d592df5b1e33e4cca7fae02379391"

      def install
        bin.install "casiusbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/casiusbot/releases/download/v1.6.0/casiusbot_1.6.0_linux_arm64.zip"
      sha256 "7ffc5bb2aa36e69c4e115cb09e0ce744a9a3c921fdcb2521b4fd7b686a4d1ee2"

      def install
        bin.install "casiusbot"
      end
    end
  end
end
