# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cornucopia < Formula
  desc "Go code generation tool"
  homepage "https://github.com/dvaumoron/cornucopia"
  version "1.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/cornucopia/releases/download/v1.2.3/cornucopia_1.2.3_darwin_amd64.zip"
      sha256 "5c8d7032f7533ae383212e21313c6436bacaae89c756652cc9b98783ea491d95"

      def install
        bin.install "cornucopia"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/cornucopia/releases/download/v1.2.3/cornucopia_1.2.3_darwin_arm64.zip"
      sha256 "996b4b04710b91abbcc58681a9395a60b1d96b18a9b0caa2b2feaf836761ac56"

      def install
        bin.install "cornucopia"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/cornucopia/releases/download/v1.2.3/cornucopia_1.2.3_linux_amd64.zip"
      sha256 "ab999ed2fa1b6b21a5f840a7f6069168e3b66e6548a313a9bdcd9ac35aeeccea"

      def install
        bin.install "cornucopia"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/cornucopia/releases/download/v1.2.3/cornucopia_1.2.3_linux_arm.zip"
      sha256 "17f966d2a84cb230ec87af90d7afbe7d743065b2d62438b414f9bff6f4f32ce5"

      def install
        bin.install "cornucopia"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/cornucopia/releases/download/v1.2.3/cornucopia_1.2.3_linux_arm64.zip"
      sha256 "7f312d841f2dadd68d1d2cc880b8893947d462dc4130079065ffe6ffca1e0ae4"

      def install
        bin.install "cornucopia"
      end
    end
  end
end
