# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosince < Formula
  desc "shows the introducing version of a Go package or symbol"
  homepage "https://github.com/dvaumoron/gosince"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/gosince/releases/download/v0.1.2/gosince_0.1.2_darwin_amd64.zip"
      sha256 "1f0e9599257c2959ada45c3463892c27dd1aaaa16a4bdf4b554b11baae110bfd"

      def install
        bin.install "gosince"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/gosince/releases/download/v0.1.2/gosince_0.1.2_darwin_arm64.zip"
      sha256 "f68f3ff334b1513b51dc0ed1ab31d45b51b7cf3289c00267f41067f707d05efd"

      def install
        bin.install "gosince"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/gosince/releases/download/v0.1.2/gosince_0.1.2_linux_amd64.zip"
      sha256 "01d40f56790aa71bb36c4ea923ec58bc97ab4fe4f76c8d8d2cd9e5c9067586fa"

      def install
        bin.install "gosince"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/gosince/releases/download/v0.1.2/gosince_0.1.2_linux_arm64.zip"
      sha256 "53867817291e78a398e71b22bc0cb57cc6bc2cf8a03221c8f186093806eb2a9e"

      def install
        bin.install "gosince"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/gosince/releases/download/v0.1.2/gosince_0.1.2_linux_arm.zip"
      sha256 "9ab545a8f039ed95245fdf94e28a8d2495e5f46852f9537d399a4240e73d3f4a"

      def install
        bin.install "gosince"
      end
    end
  end
end
