# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotofuenv < Formula
  desc "OpenTofu version manager (inspired by tofuenv, written in Go)"
  homepage "https://github.com/dvaumoron/gotofuenv"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.1.1/gotofuenv_0.1.1_darwin_amd64.zip"
      sha256 "47608f110c027192595306d858335b65098e9af974dc182b271a1422e8d99f9d"

      def install
        bin.install "gotofuenv"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.1.1/gotofuenv_0.1.1_darwin_arm64.zip"
      sha256 "e403083499235aff2eae2f3440635f2a03f26599e190b440c8c448ba390e12e6"

      def install
        bin.install "gotofuenv"
        bin.install "tofu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.1.1/gotofuenv_0.1.1_linux_arm.zip"
      sha256 "6bd89258d87f99fce486e6ccc5a3cff492aa3d41049b707d38dc8a5831591e49"

      def install
        bin.install "gotofuenv"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.1.1/gotofuenv_0.1.1_linux_arm64.zip"
      sha256 "aeea06e530520f26bc36bb352b5b5404e62922e7cda7b768fcf3fd9c1e2ec701"

      def install
        bin.install "gotofuenv"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.1.1/gotofuenv_0.1.1_linux_amd64.zip"
      sha256 "967e2fb8b7b2e95005e47d5fbe6563a9295afa79dc7b2ff383bbeafe58ae63ee"

      def install
        bin.install "gotofuenv"
        bin.install "tofu"
      end
    end
  end
end
