# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotofuenv < Formula
  desc "OpenTofu version manager (inspired by tofuenv, written in Go)"
  homepage "https://github.com/dvaumoron/gotofuenv"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.5.0/gotofuenv_0.5.0_darwin_arm64.zip"
      sha256 "d40a0e318f1480d04f6639b1100a5d7a7ef2d0aa02846d738ce5e4ee53ca2e43"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.5.0/gotofuenv_0.5.0_darwin_amd64.zip"
      sha256 "b065361955f233c713d2a15c8fb61900ee95d163283ba4c21b800daaafc2fba1"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.5.0/gotofuenv_0.5.0_linux_arm.zip"
      sha256 "ec244db8ebabbfcf13722aa579f81a64c2fd9268a6c25d203c560974a153979b"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.5.0/gotofuenv_0.5.0_linux_amd64.zip"
      sha256 "1ed43f513a87c5f1a1e6c32246f49b7be91cfd815047906ea7889f6c9088b9a5"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.5.0/gotofuenv_0.5.0_linux_arm64.zip"
      sha256 "c09236deed9dc2365c128f96c0eb6f847b40616d128d35f3060b4fc0f7e4137a"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
  end
end
