# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotofuenv < Formula
  desc "OpenTofu version manager (inspired by tofuenv, written in Go)"
  homepage "https://github.com/dvaumoron/gotofuenv"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.4.0/gotofuenv_0.4.0_darwin_arm64.zip"
      sha256 "4f1526ce634dac152e391ba996fdcc5ab066b55684f404ffff30438da43a8ca0"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.4.0/gotofuenv_0.4.0_darwin_amd64.zip"
      sha256 "3553fc7f433be54787fd65b52b8aadf2045134fc3c4c44a411d3a36ed80d3d80"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.4.0/gotofuenv_0.4.0_linux_arm.zip"
      sha256 "8fbd21e6ed131e6090aa0aad7530403a4aca584635386b0be00d88c1bd0f9841"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.4.0/gotofuenv_0.4.0_linux_amd64.zip"
      sha256 "4d1d5291deff7ea51e00c5af96d7548a2a97f451f3a6aff7723e5ceeafc756a8"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/gotofuenv/releases/download/v0.4.0/gotofuenv_0.4.0_linux_arm64.zip"
      sha256 "0fa9fd810f6d4ccf5dddc192581378940ac247be993a77946bb6eafc413a2d4f"

      def install
        bin.install "gotofuenv"
        bin.install "terraform"
        bin.install "tofu"
      end
    end
  end
end
