# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lastgo < Formula
  desc "provides an alternative go command which is a proxy keeping up to date the Go toolchain (see https://go.dev)."
  homepage "https://github.com/dvaumoron/lastgo"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/dvaumoron/lastgo/releases/download/v0.1.0/lastgo_0.1.0_darwin_amd64.zip"
      sha256 "0874149dadd32a48d4b33eac011890de27485f6a776cb4bf735025cfde6eacc7"

      def install
        bin.install "go"
      end
    end
    on_arm do
      url "https://github.com/dvaumoron/lastgo/releases/download/v0.1.0/lastgo_0.1.0_darwin_arm64.zip"
      sha256 "acb31382bb98101164ad4bbb8e3456eb91621b5156a692e5a55ba33a41dc372b"

      def install
        bin.install "go"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/lastgo/releases/download/v0.1.0/lastgo_0.1.0_linux_amd64.zip"
        sha256 "430170604b545ba51431ebb7dedf4edf58f00535170dd8de02dab040a952e72a"

        def install
          bin.install "go"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/lastgo/releases/download/v0.1.0/lastgo_0.1.0_linux_arm.zip"
        sha256 "e858810c655d89bb90fa918fbbf067ed80829d168efa5bfbdfe32121cab1ea73"

        def install
          bin.install "go"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/lastgo/releases/download/v0.1.0/lastgo_0.1.0_linux_arm64.zip"
        sha256 "f5ba70a3f6a8fe9ad79dc9486459db60da82ca16616be09fe8f6a51cca3be9a1"

        def install
          bin.install "go"
        end
      end
    end
  end
end
