# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Puzzleweaver < Formula
  desc "A ServiceWeaver (https://serviceweaver.dev) compatible modified version of PuzzleWeb (https://github.com/dvaumoron/puzzleweb), embeds all backing services"
  homepage "https://github.com/dvaumoron/puzzleweaver"
  version "1.11.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/puzzleweaver/releases/download/v1.11.3/puzzleweaver_1.11.3_darwin_amd64.zip"
      sha256 "062d9df7e7dd92ef36f4753ccd7200b265920a7b6a2d3837777ac3a443bacb7d"

      def install
        bin.install "puzzleweaver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dvaumoron/puzzleweaver/releases/download/v1.11.3/puzzleweaver_1.11.3_darwin_arm64.zip"
      sha256 "f6499f544c40cde0f2c502454ee4e05989be581a9001ea952b4d55af4c1b42e2"

      def install
        bin.install "puzzleweaver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dvaumoron/puzzleweaver/releases/download/v1.11.3/puzzleweaver_1.11.3_linux_amd64.zip"
      sha256 "5e7afbf9296bf53d52e938d26e42f49d198b3424dc3c9e098bc7afaf5f5c61f2"

      def install
        bin.install "puzzleweaver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dvaumoron/puzzleweaver/releases/download/v1.11.3/puzzleweaver_1.11.3_linux_arm64.zip"
      sha256 "b691bff4f29ea57bea9f4a7e3a7623751b5fda944b38069edfdda3baecbb871a"

      def install
        bin.install "puzzleweaver"
      end
    end
  end
end
