# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelltools < Formula
  desc "Some CLI utilities to combine within shell (inspired by https://www.nushell.sh)"
  homepage "https://github.com/dvaumoron/shelltools"
  version "0.1.4"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.4/shelltools_v0.1.4_Darwin_x86_64.tar.gz"
      sha256 "f77a9a2621ca4ff5ec605802dd88656fefc24da114776fe37cac0915edf1bf72"

      def install
        bin.install "cmdforeach"
        bin.install "cmdwithall"
        bin.install "distinctline"
        bin.install "jsonorderby"
        bin.install "jsontotable"
        bin.install "jsonwhere"
        bin.install "linetojson"
      end
    end
    on_arm do
      url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.4/shelltools_v0.1.4_Darwin_arm64.tar.gz"
      sha256 "1b1d23defb35e2d776ba533c3eb7a8b16ec715d4a1029f42778a8bb5e58fe0a7"

      def install
        bin.install "cmdforeach"
        bin.install "cmdwithall"
        bin.install "distinctline"
        bin.install "jsonorderby"
        bin.install "jsontotable"
        bin.install "jsonwhere"
        bin.install "linetojson"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.4/shelltools_v0.1.4_Linux_x86_64.tar.gz"
        sha256 "009f8b9bff70a77d34b93bf7ef601b83138a3f1ea5b50c98de7dd0f7ba888914"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "distinctline"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.4/shelltools_v0.1.4_Linux_armv6.tar.gz"
        sha256 "dd0f6f760f8afa9ff8bce75c9ec71233f87e1c8c6356eadb2cc51be53379dcac"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "distinctline"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.4/shelltools_v0.1.4_Linux_arm64.tar.gz"
        sha256 "ecabb7d1df96c07d45bfe2fbcd3ab25cec7bf6816b72eb91e0daf3eddf2e3071"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "distinctline"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
  end
end
