# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelltools < Formula
  desc "Some CLI utilities to combine within shell (inspired by https://www.nushell.sh)"
  homepage "https://github.com/dvaumoron/shelltools"
  version "0.1.1"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.1/shelltools_v0.1.1_Darwin_x86_64.tar.gz"
      sha256 "df6541c1203a8149953d1b21f2d239444f9767770d571c88df40c0ce89e689d8"

      def install
        bin.install "cmdforeach"
        bin.install "cmdwithall"
        bin.install "jsonorderby"
        bin.install "jsontotable"
        bin.install "jsonwhere"
        bin.install "linetojson"
      end
    end
    on_arm do
      url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.1/shelltools_v0.1.1_Darwin_arm64.tar.gz"
      sha256 "d9009145d0ff41088e267296679467c64f5c08e9d7b14cd9a9f35a357bb4dc08"

      def install
        bin.install "cmdforeach"
        bin.install "cmdwithall"
        bin.install "jsonorderby"
        bin.install "jsontotable"
        bin.install "jsonwhere"
        bin.install "linetojson"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.1/shelltools_v0.1.1_Linux_x86_64.tar.gz"
        sha256 "7db7e0f171261cf06cb3887f49a7f9e3f1a5efccf08cb36ef6b07495d7d281a6"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.1/shelltools_v0.1.1_Linux_armv6.tar.gz"
        sha256 "084018054aa924f30dea2dbd98358108c5c414f01d78878dce4a70dfe215d1a2"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.1/shelltools_v0.1.1_Linux_arm64.tar.gz"
        sha256 "e7bedfdb56c3715beb102dc79ce8e5a2dd83308be1e4ada357db03f2d01075e6"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
  end
end
