# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelltools < Formula
  desc "Some CLI utilities to combine within shell (inspired by https://www.nushell.sh)"
  homepage "https://github.com/dvaumoron/shelltools"
  version "0.1.5"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.5/shelltools_v0.1.5_Darwin_x86_64.tar.gz"
      sha256 "cc795f4eaff8cfe82cbc24e6dfa32ae6b4dddfd5285358f5e8d6088ca87755d2"

      def install
        bin.install "cmdforeach"
        bin.install "cmdwithall"
        bin.install "distinctline"
        bin.install "jsonorderby"
        bin.install "jsontotable"
        bin.install "jsontransform"
        bin.install "jsonwhere"
        bin.install "linetojson"
      end
    end
    on_arm do
      url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.5/shelltools_v0.1.5_Darwin_arm64.tar.gz"
      sha256 "602a4fc49445b7c0c113c46654c6cdf7877212a49927bceeec03db2cbaad0e36"

      def install
        bin.install "cmdforeach"
        bin.install "cmdwithall"
        bin.install "distinctline"
        bin.install "jsonorderby"
        bin.install "jsontotable"
        bin.install "jsontransform"
        bin.install "jsonwhere"
        bin.install "linetojson"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.5/shelltools_v0.1.5_Linux_x86_64.tar.gz"
        sha256 "fd7cf13f3e871a665542c182293d970dce905e60aec5a2b470de7f3599261649"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "distinctline"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsontransform"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.5/shelltools_v0.1.5_Linux_armv6.tar.gz"
        sha256 "fa65ac5baa775da013222e892a8bfe8cc38c850c9aa0c29efe2a4e6dd7fd0457"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "distinctline"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsontransform"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dvaumoron/shelltools/releases/download/v0.1.5/shelltools_v0.1.5_Linux_arm64.tar.gz"
        sha256 "d7303ca993759cbff346cd62432780e7c82844abe863ac3cf34d78514e886dc7"

        def install
          bin.install "cmdforeach"
          bin.install "cmdwithall"
          bin.install "distinctline"
          bin.install "jsonorderby"
          bin.install "jsontotable"
          bin.install "jsontransform"
          bin.install "jsonwhere"
          bin.install "linetojson"
        end
      end
    end
  end
end
